### ISSUE TITLE
Other Databases

### ISSUE THREAD

**Issue by thedude459** [sboulema/BrewDB#18]
I am not super well versed in databases but is it possible to make this available to other databases outside of sql lite, such as MariaDB, postgres, etc?

**Comment by phillc73** [comment]
It would add quite a lot of overhead to support multiple databases, especially those requiring a server, such as MariaDB or Postgres. Is there a specific reason why you think this would be valuable in the project, rather than something end users could accomplish themselves?

At the moment there's still so much data to input, I think multiple database support is not something that's prioritised.

**Comment by sboulema** [comment]
I agree that we should keep one master database. It is not feasible to manually update and keep multiple databases in sync.

This might be a solution though: https://www.rebasedata.com/

Users could convert the db themselves for their use case or we provide multiple databases with some scripting.

**Comment by thedude459** [comment]
I more meant the structure of the database in multiple formats so that someone could create the database and then upload any data manually.

Like you said a script in different sql database types that could create the database and then it would be on the user to import the data from the master database.

**Comment by sboulema** [comment]
🚀 

Using https://www.rebasedata.com/ and Azure Devops the master SQLite db now gets dumped into multiple db formats automagically :)

https://github.com/sboulema/BrewDB/releases
